name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy-com:
    name: Deploy COM
    runs-on: [self-hosted, production-com]
    environment: production-com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          PORT: ${{ vars.PORT }}
          AUTH_URL: ${{ vars.AUTH_URL }}
          AUTH_INTERNAL: ${{ vars.AUTH_INTERNAL }}
          APP_URL: ${{ vars.APP_URL }}
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ./build/deploy.sh

  deploy-ru:
    name: Deploy RU
    runs-on: [self-hosted, production-ru]
    environment: production-ru

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          PORT: ${{ vars.PORT }}
          AUTH_URL: ${{ vars.AUTH_URL }}
          AUTH_INTERNAL: ${{ vars.AUTH_INTERNAL }}
          APP_URL: ${{ vars.APP_URL }}
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ./build/deploy.sh
